iron_md_teleop:
  ros__parameters:
    # CAN 통신 설정
    can_interface: "can3"        # Iron-MD용 CAN 인터페이스
    can_baudrate: 250000         # 250 Kbps
    
    # 속도 제한
    max_linear_speed: 0.5        # m/s (주행)
    max_angular_speed: 1.0       # rad/s (회전)
    xyz_step_size: 0.01          # m (10mm per step)
    yaw_step_size: 0.1           # rad
    lifting_step_size: 0.05      # m (50mm per step)
    
    # 조이스틱 설정
    joystick_center: 127         # 중립값 (0-255 범위의 중간)
    joystick_deadzone: 20        # 데드존 ±20 (센터에서)
    
    # 트리거 설정
    trigger_duration: 0.5        # 초 (자동 해제)
