# Iron-MD 텔레옵 테스트용 파라미터 (노트북 can0)
# 하드웨어 없이 조종기 신호만 받아서 동작 확인

iron_md_teleop:
  ros__parameters:
    # CAN 설정 (노트북 테스트용)
    can_interface: 'can3'  # Iron-MD 조종기용 CAN 인터페이스
    can_baudrate: 250000
    
    # 주행 속도
    max_linear_speed: 0.5   # m/s
    max_angular_speed: 1.0  # rad/s
    
    # 조이스틱 설정
    joystick_center: 127    # 중립값
    joystick_deadzone: 20   # 데드존
    
    # XYZ 스테이지
    xyz_step_size: 0.01     # m, 10mm/step (조이스틱 연속 제어)
    
    # 횡이동 (S17-S18)
    lateral_move_distance: 0.05  # m, 50mm (360도 회전)
    
    # 작업 시퀀스 (S21-S22)
    z_work_distance: 0.1    # m, 100mm (작업 높이)
    gripper_open_position: 0      # 그리퍼 닫힘
    gripper_close_position: 2000  # 그리퍼 열림
    
    # Yaw 회전 (S23-S24)
    yaw_rotation_angle: 30.0  # degrees
    
    # 트리거 (S00-S01)
    trigger_duration: 0.5   # seconds
    
    # 디버그 설정
    debug_mode: true        # 터미널 상세 출력
